title: How to cope with unresponsive SME?
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://agagolan.github.io/JustTheDocs

aux_links:
  Template Repository: https://github.com/agagolan/JustTheDocs
